[build-system]
requires = [
    "setuptools >= 42",
    "setuptools_scm[toml] >= 6.2",
    "setuptools_scm_git_archive",
    "wheel >= 0.29.0",
    "cython",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "tokamesh/_version.py"
git_describe_command = "git describe --dirty --tags --long --first-parent"

[tool.cibuildwheel]
skip = ["*-win32", "*-manylinux_i686", "pp*", "*musllinux*"]
test-requires = "pytest"
test-command = "pytest {project}/tests"

[[tool.cibuildwheel.overrides]]
select = "cp36-*"
manylinux-x86_64-image = "manylinux1"
before-all = "yum install -y libjpeg-devel zlib-devel"
